# Generated by Django 5.2 on 2025-05-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materielle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepret',
            name='etat',
            field=models.CharField(choices=[('Validé', 'Validé'), ('Terminé', 'Terminé'), ('Retourner', 'Retourner')], default='Validé', max_length=20),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='etat',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En pret', 'En prêt'), ('En panne', 'En panne'), ('Repare', 'Réparé'), ('Hors service', 'Hors service'), ('Pour Salle', 'Pour Salle')], default='Disponible', max_length=20),
        ),
    ]
