# Generated by Django 5.2 on 2025-05-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materielle', '0002_alter_demandepret_etat_alter_materiel_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandepret',
            name='date_demande',
        ),
        migrations.AlterField(
            model_name='demandepret',
            name='date_debut',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='demandepret',
            name='date_fin',
            field=models.DateTimeField(),
        ),
    ]
