# Generated by Django 5.2 on 2025-05-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materielle', '0003_remove_demandepret_date_demande_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandepret',
            name='materiel',
        ),
        migrations.AddField(
            model_name='demandepret',
            name='materiel',
            field=models.ManyToManyField(to='Materielle.materiel'),
        ),
    ]
