# Generated by Django 5.2 on 2025-05-07 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materielle', '0004_remove_demandepret_materiel_demandepret_materiel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandepret',
            name='materiel',
        ),
        migrations.AddField(
            model_name='demandepret',
            name='materiel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Materielle.materiel'),
            preserve_default=False,
        ),
    ]
