# Generated by Django 5.2 on 2025-05-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materielle', '0005_remove_demandepret_materiel_demandepret_materiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date_intervention',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='etat',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En pret', 'En prêt'), ('En panne', 'En panne'), ('Repare', 'Réparé'), ('Hors service', 'Hors service'), ('En Maintenance', 'En Maintenance')], default='Disponible', max_length=20),
        ),
    ]
