# Generated by Django 5.2 on 2025-05-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materielle', '0006_alter_maintenance_date_intervention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepret',
            name='etat',
            field=models.CharField(choices=[('En cours', 'En cours'), ('En retard', 'En retard'), ('Rendu', 'Rendu')], default='Validé', max_length=20),
        ),
        migrations.AlterField(
            model_name='signalementpanne',
            name='etat',
            field=models.CharField(choices=[('Non traité', 'Non traité'), ('En cours', 'En cours'), ('Resolu', 'Resolu'), ('Non Resolu', 'Non Resolu')], default='Non traité', max_length=20),
        ),
    ]
